name: CI
on:
  push:
    branches:
      - master
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7
        with:
          node-version: '16'
      - name: Install Graphviz
        uses: tlylt/install-graphviz@b2201200d85f06f0189cb74d9b69208504cf12cd
      - name: Install Java
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0
        with:
          java-version: '11'
          distribution: 'temurin'
      - run: npm run setup
      - run: npm run test
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@ab904c41d6ece82784817410c45d8b8c02684457
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  check-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7
        with:
          node-version: '16'
      - name: Install Graphviz
        uses: tlylt/install-graphviz@b2201200d85f06f0189cb74d9b69208504cf12cd
      - name: Install Java
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0
        with:
          java-version: '11'
          distribution: 'temurin'
      - run: npm run setup
      - run: npm run build:web
      - name: Build MarkBind docs (UG + DG)
        run: npm run build:docs
      - name: Check build log
        run: |
          log_file="docs/_markbind/logs/markbind-$(date +'%Y-%m-%d').log"
          pattern="^[0-9T:.Z-]+ - (warn|error):"
          
          if grep -q -E "$pattern" "$log_file"; then
            printf "The following issues were found when building the documentation:\n"
            grep -E "$pattern" "$log_file"
            exit 1
          fi
  deploy-docs:
    needs: test
    # disabled on forks
    if: github.event_name == 'push' && github.repository == 'MarkBind/markbind'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7
        with:
          node-version: '16'
      - name: Install Graphviz
        uses: tlylt/install-graphviz@b2201200d85f06f0189cb74d9b69208504cf12cd
      - name: Install Java
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0
        with:
          java-version: '11'
          distribution: 'temurin'
      - run: npm run setup
      - name: Deploy DG on any commit to master, to markbind.org/devdocs
        run: >-
          npm run build:web &&
          npm run deploy:dg
      - name: Deploy UG on release, to markbind.org
        if: github.ref_type == 'tag'
        run: npm run deploy:ug
      - name: Check deploy log
        run: |
          log_file="docs/_markbind/logs/markbind-$(date +'%Y-%m-%d').log"
          pattern="^[0-9T:.Z-]+ - error:"
          
          if grep -q -E "$pattern" "$log_file"; then
            printf "The following issues were found when deploying the documentation:\n"
            grep -E "$pattern" "$log_file"
            exit 1
          fi
